AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Bike Shop

  SAM Template for Bike Shop

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BikeAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_products
      Handler: get_products.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /products
            Method: get

  GetOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_orders
      Handler: get_orders.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        GetOrders:
          Type: Api
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /orders
            Method: get

  GetOrderDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_order
      Handler: get_order.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        GetOrderDetails:
          Type: Api
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /orders/{id}
            Method: get

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/create_order.py
      Handler: create_order.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        CreateOrder:
          Type: Api
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /orders
            Method: post

  ProductsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: BikeProducts
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  OrdersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: Orders
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  MicroserviceApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  GetProductsFunction:
    Description: "GetProductsFunction ARN"
    Value: !GetAtt GetProductsFunction.Arn
  EndpointForGetProducts:
    Description: "API Gateway endpoint URL for Get Products function"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/products/"
  GetOrdersFunction:
    Description: "GetOrdersFunction ARN"
    Value: !GetAtt GetOrdersFunction.Arn
  EndpointForGetOrders:
    Description: "API Gateway endpoint URL for Get Orders function"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/orders/"
  GetOrderDetailsFunction:
    Description: "GetOrderDetailsFunction ARN"
    Value: !GetAtt GetOrderDetailsFunction.Arn
  EndpointForGetOrderDetails:
    Description: "API Gateway endpoint URL for Get Order Details function"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/orders/{id}"
  CreateOrderFunction:
    Description: "CreateOrderFunction ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  EndpointForCreateOrder:
    Description: "API Gateway endpoint URL for Create Order function"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/orders"
